version: "3.8"

services:
  etcd:
    image: bitnami/etcd:3.5
    container_name: milvus-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - ./volumes/etcd:/etcd-data
    networks:
      - milvus

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["minio", "server", "/minio_data", "--console-address", ":9001"]
    volumes:
      - ./volumes/minio:/minio_data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - milvus

  milvus:
    image: milvusdb/milvus:v2.4.2
    container_name: milvus-standalone
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"   # gRPC
      - "9091:9091"     # HTTP
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    networks:
      - milvus

networks:
  milvus:
    driver: bridge